services:
  # Main Clutch Platform Backend
  - type: web
    name: clutch-platform-backend
    env: node
    plan: starter
    buildCommand: cd shared-backend && npm install && npm run build
    startCommand: cd shared-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: clutch-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: ziad@yourclutch.com
      - key: ADMIN_PASSWORD_HASH
        value: $2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/8K.8.8.
      - key: REDIS_URL
        fromService:
          type: redis
          name: clutch-redis
          property: connectionString
      - key: DB_MAX_POOL_SIZE
        value: 100
      - key: DB_MIN_POOL_SIZE
        value: 10
      - key: BCRYPT_ROUNDS
        value: 12
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: .

  # Clutch Admin Dashboard
  - type: web
    name: clutch-admin-dashboard
    env: node
    plan: starter
    buildCommand: cd clutch-admin && npm install && npm run build
    startCommand: cd clutch-admin && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: REACT_APP_API_URL
        value: https://clutch-main-nk7x.onrender.com
    autoDeploy: true
    branch: main
    rootDir: .

  # Clutch Auto Parts System
  - type: web
    name: clutch-auto-parts
    env: node
    plan: starter
    buildCommand: cd clutch-auto-parts-clean && npm install && npm run build
    startCommand: cd clutch-auto-parts-clean && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: REACT_APP_API_URL
        value: https://clutch-main-nk7x.onrender.com
    autoDeploy: true
    branch: main
    rootDir: .

  # Clutch Website
  - type: web
    name: clutch-website
    env: static
    plan: starter
    buildCommand: cd website && npm install && npm run build
    staticPublishPath: ./website/dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: .

databases:
  # Main MongoDB Database
  - name: clutch-database
    plan: starter
    databaseName: clutch_production
    user: clutch_user

  # Redis Cache
  - name: clutch-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

# Environment Variables
envVars:
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: CORS_ORIGIN
    value: https://clutch-main-nk7x.onrender.com
  - key: RATE_LIMIT_WINDOW_MS
    value: 900000
  - key: RATE_LIMIT_MAX_REQUESTS
    value: 100