'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string, params?: any) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<'en' | 'ar'>('en');

  // Load language from localStorage on mount and apply RTL immediately
  useEffect(() => {
    const savedLanguage = localStorage.getItem('clutch-language') as 'en' | 'ar';
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage);
      // Apply RTL immediately on mount
      if (savedLanguage === 'ar') {
        document.documentElement.dir = 'rtl';
        document.documentElement.lang = 'ar';
      } else {
        document.documentElement.dir = 'ltr';
        document.documentElement.lang = 'en';
      }
    }
  }, []);

  // Apply RTL direction whenever language changes
  useEffect(() => {
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = 'en';
    }
  }, [language]);

  // Save language to localStorage when it changes
  const setLanguage = (lang: 'en' | 'ar') => {
    setLanguageState(lang);
    localStorage.setItem('clutch-language', lang);
  };

  // Translation function with fallback
  const t = (key: string, params?: any) => {
    // Try to load translations from JSON files
    let translations: Record<string, string> = {};
    
    try {
      if (language === 'ar') {
        // Load Arabic translations
        const arTranslations = require('@/messages/ar.json');
        translations = arTranslations;
      } else {
        // Load English translations
        const enTranslations = require('@/messages/en.json');
        translations = enTranslations;
      }
    } catch (error) {
      console.warn('Failed to load translation files, using fallback:', error);
    }

    // Fallback translations if loading fails
    const fallbackTranslations: Record<string, string> = {
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.add': 'Add',
      'common.search': 'Search...',
      'common.filter': 'Filter',
      'common.export': 'Export',
      'common.import': 'Import',
      'common.refresh': 'Refresh',
      'common.close': 'Close',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.previous': 'Previous',
      'common.submit': 'Submit',
      'common.reset': 'Reset',
      'common.confirm': 'Confirm',
      'common.yes': 'Yes',
      'common.no': 'No',
      'navigation.dashboard': 'Dashboard',
      'navigation.userManagement': 'User Management',
      'navigation.fleetManagement': 'Fleet Management',
      'navigation.crm': 'CRM',
      'navigation.chat': 'Chat',
      'navigation.aiDashboard': 'AI Dashboard',
      'navigation.enterprise': 'Enterprise',
      'navigation.finance': 'Finance',
      'navigation.legal': 'Legal',
      'navigation.hr': 'HR',
      'navigation.featureFlags': 'Feature Flags',
      'navigation.communication': 'Communication',
      'navigation.analytics': 'Analytics',
      'navigation.mobileApps': 'Mobile Apps',
      'navigation.cms': 'CMS',
      'navigation.marketing': 'Marketing',
      'navigation.projects': 'Projects',
      'navigation.settings': 'Settings',
      'navigation.reports': 'Reports',
      'navigation.integrations': 'Integrations',
      'navigation.auditTrail': 'Audit Trail',
      'navigation.apiDocs': 'API Docs',
      'navigation.assets': 'Assets',
      'navigation.vendors': 'Vendors',
        'navigation.systemHealth': 'System Health',
        // Sidebar translations
        'sidebar.collapse': 'Collapse',
        // Theme translations
        'theme.toggle': 'Toggle theme',
        'theme.light': 'Light',
        'theme.dark': 'Dark',
        'theme.system': 'System',
        // Header translations
        'header.search': 'Search...',
        'header.notifications': 'Notifications',
        'header.myAccount': 'My Account',
        'header.profile': 'Profile',
        'header.settings': 'Settings',
        'header.language': 'Language',
        // Common translations
        'search': 'Search...',
        'conversionRate': 'Conversion Rate',
        'operationsTrendingPositive': 'Operations trending positive',
        'excellent': 'Excellent',
        'fleetOperations': 'Fleet Operations',
        'infrastructure': 'Infrastructure',
        'maintenance': 'Maintenance',
        'other': 'Other',
        'ofTotalCosts': 'of total costs',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'none': 'None',
        'overallComplianceStatus': 'Overall Compliance Status',
        'pendingApprovals': 'Pending Approvals',
        'violations': 'Violations',
        'securityIncidents': 'Security Incidents',
        'complianceBreakdown': 'Compliance Breakdown',
        'awaitingReview': 'Awaiting Review',
        'complianceViolations': 'Compliance Violations',
        'policyBreaches': 'Policy Breaches',
        'securityBreaches': 'Security Breaches',
        'auditTimeline': 'Audit Timeline',
        'lastAudit': 'Last Audit',
        'completedSuccessfully': 'Completed successfully',
        'passed': 'Passed',
        'nextAudit': 'Next Audit',
        'scheduledAudit': 'Scheduled audit',
        'complianceProgress': 'Compliance Progress',
        'overallCompliance': 'Overall Compliance',
        'exportReport': 'Export Report',
        'complianceInsights': 'Compliance Insights',
        'someAreasNeedAttention': 'Some areas need attention - review pending approvals',
        'nextAuditIn': 'Next audit in {days} days',
        'approvalsPendingReview': '{count} approvals pending review',
        'violationsNeedResolution': '{count} compliance violations need resolution',
        'top5EnterpriseClients': 'Top 5 Enterprise Clients',
        'byRevenueContribution': 'By revenue contribution & activity level',
        'totalRevenue': 'Total Revenue',
        'avgGrowth': 'Avg Growth',
        'revenueDistribution': 'Revenue Distribution',
        'growthAnalysis': 'Growth Analysis',
        'growingClients': 'Growing Clients',
        'decliningClients': 'Declining Clients',
        'viewAllClients': 'View All Clients',
        'scheduleReview': 'Schedule Review',
        'clientInsights': 'Client Insights',
        'topClientContributes': 'Top client contributes {percentage}% of total revenue',
        'clientsShowingGrowth': '{growing} out of {total} clients showing positive growth',
        'averageClientActivity': 'Average client activity level: {percentage}%',
        'totalEnterpriseRevenue': 'Total enterprise revenue: {amount} EGP',
        // User management widget translations
        'widgets.userGrowthCohort': 'User Growth Cohort',
        'widgets.engagementHeatmap': 'Engagement Heatmap',
        'widgets.onboardingCompletion': 'Onboarding Completion',
        'widgets.roleDistribution': 'Role Distribution',
        'widgets.retained': 'Retained',
        'widgets.retentionRate': 'Retention Rate',
        'widgets.cohortAnalysis': 'Cohort Analysis',
        'widgets.tracksNewSignups': 'Tracks new signups vs retained users per month',
        'widgets.loadingCohortAnalysis': 'Loading cohort analysis...',
        'widgets.noCohortData': 'No cohort data available',
        'widgets.loadingHeatmapData': 'Loading engagement heatmap...',
        'widgets.noHeatmapData': 'No engagement data available',
        'widgets.loadingRoleData': 'Loading role distribution...',
        'widgets.noRoleData': 'No role data available',
        'widgets.loadingOnboardingData': 'Loading onboarding completion...',
        'widgets.noOnboardingData': 'No onboarding data available',
      
      // Dashboard specific translations
      'dashboard.title': 'Dashboard',
      'dashboard.welcome': 'Welcome to your Clutch Admin dashboard',
      'dashboard.loadingDashboard': 'Loading dashboard...',
      'dashboard.realTime': 'Real-time',
      'dashboard.live': 'Live',
      'dashboard.messages': 'msgs',
      'dashboard.generateReport': 'Generate Report',
      'dashboard.exportData': 'Export Data',
      'dashboard.refresh': 'Refresh',
      'dashboard.realtimeActivityFeed': 'Real-time Activity Feed',
      'dashboard.latestActionsAndEvents': 'Latest actions and system events',
      'dashboard.quickActions': 'Quick Actions',
      'dashboard.commonAdministrativeTasks': 'Common administrative tasks',
      'dashboard.fleetStatus': 'Fleet Status',
      'dashboard.realtimeFleetMonitoring': 'Real-time fleet monitoring',
      'dashboard.noLocation': 'No location',
      'dashboard.performanceMetrics': 'Performance Metrics',
      'dashboard.apiUptimeRequestsErrorsSessions': 'API uptime and requests, errors, and sessions',
      'dashboard.apiUptime': 'API Uptime',
      'dashboard.requestRate': 'Request Rate',
      'dashboard.errorRate': 'Error Rate',
      'dashboard.activeSessions': 'Active Sessions',
      'dashboard.systemAlerts': 'System Alerts',
      'dashboard.criticalNotificationsRequiringAttention': 'Critical notifications requiring attention',
      'dashboard.noAlerts': 'No alerts at this time',
      'dashboard.businessIntelligence': 'Business Intelligence',
      'dashboard.advancedAnalyticsAndPredictiveInsights': 'Advanced analytics and predictive insights for data-driven decisions',
      
      // Widget translations
      'widgets.unifiedOpsPulse': 'Unified Ops Pulse',
      'widgets.realTimeOperationalFunnel': 'Real-time Operational Funnel',
      'widgets.newUsers30d': 'New Users (30d)',
      'widgets.freshSignups': 'Fresh signups',
      'widgets.activeSessions': 'Active Sessions',
      'widgets.currentlyOnline': 'Currently online',
      'widgets.activeVehicles': 'Active Vehicles',
      'widgets.fleetUtilization': 'Fleet utilization',
      'widgets.revenueImpact': 'Revenue Impact',
      'widgets.revenue Impact': 'Revenue Impact',
      'widgets.monthlyRevenue': 'Monthly revenue',
      'widgets.conversionRate': 'Conversion Rate',
      'widgets.efficiency': 'Efficiency',
      'widgets.operationsTrendingPositive': 'Operations trending positive',
      'widgets.churnRiskAnalysis': 'Churn Risk Analysis',
      'widgets.aiPoweredPrediction': 'AI-powered prediction of customer churn risk',
      'widgets.highRisk': 'High Risk',
      'widgets.mediumRisk': 'Medium Risk',
      'widgets.totalAtRisk': 'Total at Risk',
      'widgets.sendRetentionCampaign': 'Send Retention Campaign',
      'widgets.viewAllUsers': 'View All Users',
      'widgets.revenueVsCostMargin': 'Revenue vs Cost Margin',
      'widgets.revenueVsCosts': 'Revenue vs Costs',
      'widgets.monthlyCosts': 'Monthly Costs',
      'widgets.netProfitMargin': 'Net Profit Margin',
      'widgets.costBreakdown': 'Cost Breakdown',
      'widgets.fleetOperations': 'Fleet Operations',
      'widgets.infrastructure': 'Infrastructure',
      'widgets.maintenance': 'Maintenance',
      'widgets.other': 'Other',
      'widgets.aiPoweredForecast': 'AI-Powered Forecast',
      'widgets.nextPeriodRevenueProjection': 'Next Period Revenue Projection',
      'widgets.projectedRevenue': 'Projected Revenue',
      'widgets.baseCase': 'Base Case',
      'widgets.avgConfidence': 'Avg Confidence',
      'widgets.lowRisk': 'Low Risk',
      'widgets.scenarioAnalysis': 'Scenario Analysis',
      'widgets.optimistic': 'Optimistic',
      'widgets.pessimistic': 'Pessimistic',
      'widgets.dailyForecastTrend': 'Daily Forecast Trend',
      'widgets.keyFactors': 'Key Factors',
      'widgets.riskAssessment': 'Risk Assessment',
      'widgets.viewDetails': 'View Details',
      'widgets.setTargets': 'Set Targets',
      'widgets.top5EnterpriseClients': 'Top 5 Enterprise Clients',
      'widgets.byRevenueContribution': 'By revenue contribution & activity level',
      'widgets.totalRevenue': 'Total Revenue',
      'widgets.avgGrowth': 'Avg Growth',
      'widgets.viewAllClients': 'View All Clients',
      'widgets.scheduleReview': 'Schedule Review',
      'widgets.clientInsights': 'Client Insights',
      
      // Status and quality indicators
      'status.excellent': 'Excellent',
      'status.good': 'Good',
      'status.needsAttention': 'Needs Attention',
      'status.poor': 'Poor',
      'status.critical': 'Critical',
      'status.warning': 'Warning',
      'status.info': 'Info',
      'status.success': 'Success',
      'status.error': 'Error',
      
      // Time periods
      'time.days': 'Days',
      'time.hours': 'Hours',
      'time.minutes': 'Minutes',
      'time.seconds': 'Seconds',
      'time.weeks': 'Weeks',
      'time.months': 'Months',
      'time.years': 'Years',
      
      // Common actions
      'actions.view': 'View',
      'actions.edit': 'Edit',
      'actions.delete': 'Delete',
      'actions.create': 'Create',
      'actions.update': 'Update',
      'actions.save': 'Save',
      'actions.cancel': 'Cancel',
      'actions.submit': 'Submit',
      'actions.reset': 'Reset',
      'actions.refresh': 'Refresh',
      'actions.export': 'Export',
      'actions.import': 'Import',
      'actions.download': 'Download',
      'actions.upload': 'Upload',
      'actions.print': 'Print',
      'actions.share': 'Share',
      'actions.copy': 'Copy',
      'actions.paste': 'Paste',
      'actions.cut': 'Cut',
      'actions.undo': 'Undo',
      'actions.redo': 'Redo',
      'common.connecting': 'Connecting',
      'common.offline': 'Offline',
      'common.closing': 'Closing',
      'common.unknown': 'Unknown',
      'common.view': 'View',
      'common.manage': 'Manage',
      
      // CMS Help translations
      'cms.help.title': 'Help Articles CMS',
      'cms.help.description': 'Manage and organize help articles for your users',
      'cms.help.newArticle': 'New Article',
      'cms.help.searchPlaceholder': 'Search articles...',
      'cms.help.allCategories': 'All Categories',
      'cms.help.articles': 'Articles',
      'cms.help.views': 'views',
      'cms.help.updated': 'Updated',
      'cms.help.tabs.articles': 'Articles',
      'cms.help.tabs.categories': 'Categories',
      'cms.help.tabs.analytics': 'Analytics',
      'cms.help.categories.gettingStarted': 'Getting Started',
      'cms.help.categories.fleetManagement': 'Fleet Management',
      'cms.help.categories.billing': 'Billing',
      'cms.help.categories.technicalSupport': 'Technical Support',
      'cms.help.tags.basics': 'Basics',
      'cms.help.tags.tutorial': 'Tutorial',
      'cms.help.tags.fleet': 'Fleet',
      'cms.help.tags.management': 'Management',
      'cms.help.tags.billing': 'Billing',
      'cms.help.tags.payment': 'Payment',
      'cms.help.sampleArticles.gettingStarted.title': 'Getting Started with Clutch',
      'cms.help.sampleArticles.gettingStarted.content': 'Learn the basics of using Clutch for fleet management. This guide covers account setup, navigation, and essential features.',
      'cms.help.sampleArticles.fleetManagement.title': 'Fleet Management Best Practices',
      'cms.help.sampleArticles.fleetManagement.content': 'Discover how to effectively manage your fleet with Clutch. Learn about vehicle tracking, maintenance scheduling, and performance monitoring.',
      'cms.help.sampleArticles.billing.title': 'Understanding Your Billing',
      'cms.help.sampleArticles.billing.content': 'Everything you need to know about billing, payments, and subscription management in Clutch.',
      'cms.help.analytics.totalArticles': 'Total Articles',
      'cms.help.analytics.published': 'Published',
      'cms.help.analytics.totalViews': 'Total Views',
      'cms.help.analytics.categories': 'Categories',
      
      // CRM translations
      'crm.title': 'CRM Dashboard',
      'crm.description': 'Manage customer relationships and interactions',
      'crm.loadingData': 'Loading CRM data...',
      'crm.analytics': 'Analytics',
      'crm.addCustomer': 'Add Customer',
      'crm.totalCustomers': 'Total Customers',
      'crm.activeCustomers': 'Active Customers',
      'crm.openTickets': 'Open Tickets',
      'crm.avgSatisfaction': 'Avg Satisfaction',
      'crm.fromLastMonth': 'from last month',
      'crm.retentionRate': 'retention rate',
      'crm.fromYesterday': 'from yesterday',
      'crm.customerProfiles': 'Customer Profiles',
      'crm.ticketManagement': 'Ticket Management',
      'crm.communicationHistory': 'Communication History',
      'crm.manageCustomerInfo': 'Manage customer information and relationships',
      'crm.searchCustomers': 'Search customers...',
      'crm.filterByStatus': 'Filter by status',
      'crm.allStatus': 'All Status',
      'crm.active': 'Active',
      'crm.prospect': 'Prospect',
      'crm.inactive': 'Inactive',
      'crm.customer': 'Customer',
      'crm.company': 'Company',
      'crm.status': 'Status',
      'crm.totalSpent': 'Total Spent',
      'crm.satisfaction': 'Satisfaction',
      'crm.lastContact': 'Last Contact',
      'crm.viewProfile': 'View Profile',
      'crm.sendMessage': 'Send Message',
      'crm.callCustomer': 'Call Customer',
      'crm.scheduleMeeting': 'Schedule Meeting',
      'crm.viewActivity': 'View Activity',
      'crm.supportTickets': 'Support Tickets',
      'crm.manageCustomerSupport': 'Manage customer support tickets',
      'crm.ticket': 'Ticket',
      'crm.priority': 'Priority',
      'crm.assignedTo': 'Assigned To',
      'crm.created': 'Created',
      'crm.viewDetails': 'View Details',
      'crm.assignToMe': 'Assign to Me',
      'crm.markAsResolved': 'Mark as Resolved',
      'crm.escalate': 'Escalate',
      'crm.timelineOfInteractions': 'Timeline of all customer interactions',
      'crm.phoneCall': 'Phone Call',
      'crm.hoursAgo': 'hours ago',
      'crm.discussedFleetFeatures': 'Discussed fleet management features and pricing options',
      'crm.email': 'Email',
      'crm.dayAgo': 'day ago',
      'crm.sentMonthlyReport': 'Sent monthly usage report and recommendations',
      'crm.meeting': 'Meeting',
      'crm.daysAgo': 'days ago',
      'crm.productDemoCompleted': 'Product demo and onboarding session completed',
      'crm.crmAnalytics': 'CRM Analytics',
      'crm.moveBeyondTickets': 'Move beyond tickets to understand customer health and opportunities',
      
      // Reports translations
      'reports.title': 'Reports',
      'reports.description': 'Generate and manage business reports',
      'reports.loadingReports': 'Loading reports...',
      'reports.reportTemplates': 'Report Templates',
      'reports.createReport': 'Create Report',
      'reports.generateReport': 'Generate Report',
      'reports.totalReports': 'Total Reports',
      'reports.completed': 'Completed',
      'reports.scheduled': 'Scheduled',
      'reports.availableTemplates': 'Available templates',
      'reports.scheduledReports': 'Scheduled Reports',
      'reports.autoGeneratedReports': 'Auto-generated reports',
      'reports.dataProcessed': 'Data Processed',
      'reports.totalRecordsProcessed': 'Total records processed',
      'reports.reports': 'Reports',
      'reports.manageAndViewReports': 'Manage and view all your business reports',
      'reports.reportType': 'Report Type',
      'reports.financial': 'Financial',
      'reports.operational': 'Operational',
      'reports.userAnalytics': 'User Analytics',
      'reports.fleet': 'Fleet',
      'reports.status': 'Status',
      'reports.generating': 'Generating',
      'reports.failed': 'Failed',
      'reports.createdBy': 'Created By',
      'reports.schedule': 'Schedule',
      'reports.records': 'Records',
      'reports.fileSize': 'File Size',
      'reports.createdAt': 'Created At',
      'reports.generatedAt': 'Generated At',
      'reports.nextRun': 'Next Run',
      'reports.downloadReport': 'Download Report',
      'reports.viewReport': 'View Report',
      'reports.createReportDescription': 'Create a new business report with custom parameters',
      'reports.reportName': 'Report Name',
      'reports.enterReportName': 'Enter report name',
      'reports.reportDescription': 'Report Description',
      'reports.startDate': 'Start Date',
      'reports.endDate': 'End Date',
      'reports.once': 'Once',
      'reports.daily': 'Daily',
      'reports.weekly': 'Weekly',
      'reports.monthly': 'Monthly',
      'reports.quarterly': 'Quarterly',
      'reports.useTemplatesDescription': 'Use pre-built templates to quickly create reports',
      'reports.usedTimes': 'Used {count} times',
      'reports.useTemplate': 'Use Template',
      'reports.reportsAnalytics': 'Reports Analytics',
      'reports.automateAndMeasure': 'Automate and measure your reporting efficiency',
      'reports.currentUser': 'Current User',
      'reports.custom': 'Custom',
      
      // Quick Actions translations
      'quickActions.navigatingToUserManagement': 'Navigating to User Management',
      'quickActions.navigatingToFleetManagement': 'Navigating to Fleet Management',
      'quickActions.navigatingToAnalytics': 'Navigating to Analytics',
      'quickActions.navigatingToReports': 'Navigating to Reports',
      'quickActions.navigatingToSettings': 'Navigating to Settings',
      'quickActions.navigatingToCRM': 'Navigating to CRM',
      'quickActions.navigatingToFinance': 'Navigating to Finance',
      'quickActions.generatingReport': 'Generating report...',
      'quickActions.dashboardReport': 'Dashboard Report',
      'quickActions.reportGeneratedSuccessfully': 'Report generated successfully!',
      'quickActions.failedToGenerateReport': 'Failed to generate report',
      'quickActions.exportingData': 'Exporting data...',
      'quickActions.dataExportedSuccessfully': 'Data exported successfully!',
      'quickActions.failedToExportData': 'Failed to export data',
      'quickActions.openingUserCreationForm': 'Opening user creation form',
      'quickActions.openingFleetCreationForm': 'Opening fleet creation form',
      'quickActions.optimizingRoutes': 'Optimizing routes...',
      'quickActions.routesOptimizedSuccessfully': 'Routes optimized successfully!',
      'quickActions.routesOptimized': 'routes optimized',
      'quickActions.failedToOptimizeRoutes': 'Failed to optimize routes',
      'quickActions.refreshingData': 'Refreshing data...',
      'quickActions.dataRefreshedSuccessfully': 'Data refreshed successfully!',
      'quickActions.failedToRefreshData': 'Failed to refresh data',
      'quickActions.sendingNotification': 'Sending notification...',
      'quickActions.notificationSentSuccessfully': 'Notification sent successfully!',
      'quickActions.failedToSendNotification': 'Failed to send notification',
      
      'auth.login': 'Login',
      'auth.logout': 'Logout',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.forgotPassword': 'Forgot Password?',
      'auth.rememberMe': 'Remember Me',
      'auth.signIn': 'Sign In',
      'auth.signUp': 'Sign Up',
      'auth.welcome': 'Welcome',
      'auth.welcomeBack': 'Welcome Back',
      'auth.invalidCredentials': 'Invalid email or password',
      'auth.loginSuccess': 'Login successful',
      'auth.logoutSuccess': 'Logout successful',
      'auth.signingIn': 'Signing in...',
      'auth.errorOccurred': 'An error occurred. Please try again.',
      'language.english': 'English',
      'language.arabic': 'Arabic',
      'header.language': 'Language',
      'header.search': 'Search',
      'header.notifications': 'Notifications',
      'header.myAccount': 'My Account',
      'header.profile': 'Profile',
      'header.settings': 'Settings',
      'sidebar.clutchAdmin': 'Clutch Admin',
      'sidebar.collapse': 'Collapse',
      'sidebar.expand': 'Expand',
      'analytics.title': 'Analytics',
      'analytics.overview': 'Analytics Overview',
      'analytics.description': 'Comprehensive analytics and insights for your platform',
      'analytics.loadingAnalytics': 'Loading analytics...',
      'analytics.failedToLoadAnalytics': 'Failed to load analytics data',
      'analytics.generateReport': 'Generate Report',
      'analytics.exportData': 'Export Data',
      'analytics.refresh': 'Refresh',
      'analytics.searchAnalytics': 'Search analytics...',
      'analytics.filterByTimeRange': 'Filter by time range',
      'analytics.timeRange': 'Time Range',
      'analytics.last7Days': 'Last 7 days',
      'analytics.last30Days': 'Last 30 days',
      'analytics.last90Days': 'Last 90 days',
      'analytics.lastYear': 'Last year',
      'analytics.customRange': 'Custom range',
      'analytics.userAnalytics': 'User Analytics',
      'analytics.revenueAnalytics': 'Revenue Analytics',
      'analytics.fleetAnalytics': 'Fleet Analytics',
      'analytics.engagementAnalytics': 'Engagement Analytics',
      'analytics.reports': 'Reports',
      'analytics.totalUsers': 'Total Users',
      'analytics.activeUsers': 'Active Users',
      'analytics.newUsers': 'New Users',
      'analytics.userGrowth': 'User Growth',
      'analytics.totalRevenue': 'Total Revenue',
      'analytics.monthlyRecurringRevenue': 'Monthly Recurring Revenue',
      'analytics.averageRevenuePerUser': 'Average Revenue Per User',
      'analytics.revenueGrowth': 'Revenue Growth',
      'analytics.totalFleet': 'Total Fleet',
      'analytics.activeFleet': 'Active Fleet',
      'analytics.fleetUtilization': 'Fleet Utilization',
      'analytics.fleetGrowth': 'Fleet Growth',
      'analytics.totalSessions': 'Total Sessions',
      'analytics.averageSessionDuration': 'Average Session Duration',
      'analytics.bounceRate': 'Bounce Rate',
      'analytics.engagementRate': 'Engagement Rate',
      'users.title': 'User Management',
      'users.overview': 'User Overview',
      'users.description': 'Manage users, roles, and permissions',
      'users.loadingUsers': 'Loading users...',
      'users.failedToLoadUsers': 'Failed to load users',
      'users.addUser': 'Add User',
      'users.totalUsers': 'Total Users',
      'users.activeUsers': 'Active Users',
      'users.suspendedUsers': 'Suspended Users',
      'users.searchUsers': 'Search users...',
      'users.filterByStatus': 'Filter by status',
      'users.filterByRole': 'Filter by role',
      'users.allStatuses': 'All Statuses',
      'users.allRoles': 'All Roles',
      'users.active': 'Active',
      'users.suspended': 'Suspended',
      'users.pending': 'Pending',
      'users.platformAdmin': 'Platform Admin',
      'users.enterpriseClient': 'Enterprise Client',
      'users.serviceProvider': 'Service Provider',
      'users.b2cCustomer': 'B2C Customer',
      'users.b2c': 'B2C',
      'users.b2b': 'B2B',
      'users.providers': 'Providers',
      'users.name': 'Name',
      'users.email': 'Email',
      'users.role': 'Role',
      'users.status': 'Status',
      'users.lastLogin': 'Last Login',
      'users.createdAt': 'Created At',
      'users.actions': 'Actions',
      'users.editUser': 'Edit User',
      'users.deleteUser': 'Delete User',
      'users.suspendUser': 'Suspend User',
      'users.activateUser': 'Activate User',
      'users.viewProfile': 'View Profile',
      'users.sendEmail': 'Send Email',
      'users.noUsersFound': 'No users found',
      'users.userGrowth': 'User Growth',
      'users.engagement': 'Engagement',
      'users.onboarding': 'Onboarding',
      'users.roleDistribution': 'Role Distribution',
      'users.churnRisk': 'Churn Risk',
      'widgets.loadingOperationalMetrics': 'Loading operational metrics...',
      'widgets.unableToLoadOperationalMetrics': 'Unable to load operational metrics',
      'widgets.newUsers': 'New Users',
      'widgets.activeUsers': 'Active Users',
      'widgets.fleetVehicles': 'Fleet Vehicles',
      'widgets.operationalPulse': 'Operational Pulse',
      'widgets.overallEfficiency': 'Overall Efficiency',
      'widgets.churnRisk': 'Churn Risk',
      'widgets.critical': 'Critical',
      'widgets.warning': 'Warning',
      'widgets.stable': 'Stable',
      'widgets.margin': 'Margin',
      'widgets.profitability': 'Profitability',
      'widgets.forecast': 'Forecast',
      'widgets.aiPowered': 'AI-Powered',
      'widgets.next7Days': 'Next 7 Days',
      'widgets.next30Days': 'Next 30 Days',
      'widgets.next90Days': 'Next 90 Days',
      'widgets.complianceStatus': 'Compliance Status',
      'widgets.enterpriseClients': 'Enterprise Clients',
      'widgets.topClients': 'Top Clients',
      'widgets.revenueGrowth': 'Revenue Growth',
      'widgets.noData': 'No data available',
      'widgets.refresh': 'Refresh',
      'widgets.fromLastPeriod': 'from last period',
      'widgets.noLocationData': 'No location data',
      'widgets.noAlertsAtThisTime': 'No alerts at this time',
      'widgets.monthlyRevenuePredictions': 'Monthly revenue predictions',
      'widgets.allClear': 'All Clear',
      'widgets.attentionNeeded': 'Attention Needed',
      'widgets.actionRequired': 'Action Required',
      'widgets.high': 'High',
      'widgets.medium': 'Medium',
      'widgets.low': 'Low',
      'widgets.none': 'None',
      'widgets.overdue': 'Overdue',
      'widgets.days': 'days',
      'widgets.excellent': 'Excellent',
      'widgets.good': 'Good',
      'widgets.fair': 'Fair',
      'widgets.poor': 'Poor',
      'widgets.today': 'Today',
      'widgets.yesterday': 'Yesterday',
      'widgets.viewUserDetails': 'View User Details',
      'widgets.sendEmail': 'Send Email',
      'widgets.callUser': 'Call User',
      'widgets.needsAttention': 'Needs Attention',
      'widgets.forecastHighConfidence': 'Forecast shows high confidence with stable growth patterns.',
      'widgets.forecastModerateConfidence': 'Moderate confidence with some variability in projections.',
      'widgets.forecastHighUncertainty': 'High uncertainty - consider additional data sources.',
      'quickActions.refreshAllDashboardData': 'Refresh all dashboard data',
      'quickActions.viewCRM': 'View CRM',
      'quickActions.openCustomerRelationshipManagement': 'Open customer relationship management',
      'quickActions.viewFinance': 'View Finance',
      'quickActions.openFinancialDashboard': 'Open financial dashboard',
      'quickActions.viewSettings': 'View Settings',
      'quickActions.openSystemSettings': 'Open system settings',
      
      // Quick Actions button titles (missing ones)
      'quickActions.addUser': 'Add User',
      'quickActions.createFleet': 'Create Fleet',
      'quickActions.generateReport': 'Generate Report',
      'quickActions.viewAnalytics': 'View Analytics',
      'quickActions.optimizeRoutes': 'Optimize Routes',
      'quickActions.exportData': 'Export Data',
      'quickActions.refreshData': 'Refresh Data',
      
      'widgets.invalidDataStructure': 'Invalid compliance data structure',
      'widgets.complianceStatusSummary': 'Compliance status summary across all areas',
      'widgets.complianceRadar': 'Compliance Radar',
      'widgets.pendingApprovals': 'Pending Approvals',
      'widgets.violations': 'Violations',
      'widgets.securityIncidents': 'Security Incidents',
      'widgets.complianceBreakdown': 'Compliance Breakdown',
      'widgets.awaitingReview': 'Awaiting Review',
      'widgets.complianceViolations': 'Compliance Violations',
      'widgets.policyBreaches': 'Policy Breaches',
      'widgets.securityBreaches': 'Security Breaches',
      'widgets.loading': 'Loading compliance status...',
      'widgets.dataStructureError': 'Data structure error - Check console for details',
      'widgets.dataFormatMismatch': 'The compliance data received does not match the expected format.',
      'widgets.unableToLoad': 'Unable to load compliance status',
      'widgets.auditTimeline': 'Audit Timeline',
      'widgets.lastAudit': 'Last Audit',
      'widgets.completedSuccessfully': 'Completed successfully',
      'widgets.passed': 'Passed',
      'widgets.nextAudit': 'Next Audit',
      'widgets.scheduledAudit': 'Scheduled audit',
      'widgets.complianceProgress': 'Compliance Progress',
      'widgets.overallCompliance': 'Overall Compliance',
      'widgets.exportReport': 'Export Report',
      'widgets.complianceInsights': 'Compliance Insights',
      'widgets.allRequirementsMet': 'All compliance requirements are met',
      'widgets.attentionNeededAreas': 'Some areas need attention - review pending approvals',
      'widgets.immediateActionRequired': 'Immediate action required - address violations and incidents',
      'widgets.nextAuditIn': 'Next audit in {days} days',
      'widgets.approvalsPendingReview': '{count} approvals pending review',
      'widgets.violationsNeedResolution': '{count} compliance violations need resolution',
      
      // Enterprise translations
      'enterprise.revenueDistribution': 'Revenue Distribution',
      'enterprise.growthAnalysis': 'Growth Analysis',
      'enterprise.growingClients': 'Growing Clients',
      'enterprise.decliningClients': 'Declining Clients',
      'enterprise.viewAllClients': 'View All Clients',
      'enterprise.scheduleReview': 'Schedule Review',
      'enterprise.clientInsights': 'Client Insights',
      'enterprise.topClientContributes': 'Top client contributes {percentage}% of total revenue',
      'enterprise.clientsShowingGrowth': '{count} out of {total} clients showing positive growth',
      'enterprise.averageClientActivity': 'Average client activity level: {percentage}%',
      'enterprise.totalEnterpriseRevenue': 'Total enterprise revenue: {amount}',
      
      // Notifications translations
      'notifications.noNotifications': 'No notifications at this time',
  
  // Navigation translations
  'navigation.dashboard': 'Dashboard',
  'navigation.usermanagement': 'User Management',
  'navigation.fleetmanagement': 'Fleet Management',
  'navigation.crm': 'CRM',
  'navigation.chat&messaging': 'Chat & Messaging',
  'navigation.ai&mldashboard': 'AI & ML Dashboard',
  'navigation.enterpriseb2b': 'Enterprise B2B',
  'navigation.finance': 'Finance',
  'navigation.legal': 'Legal',
  'navigation.hr': 'HR',
  'navigation.featureflags': 'Feature Flags',
  'navigation.communication': 'Communication',
  'navigation.analytics': 'Analytics',
  'navigation.mobileapps': 'Mobile Apps',
  'navigation.cms': 'CMS',
  'navigation.marketing': 'Marketing',
  'navigation.projectmanagement': 'Project Management',
  'navigation.settings': 'Settings',
  'navigation.reporting': 'Reporting',
  'navigation.integrations': 'Integrations',
  'navigation.audittrail': 'Audit Trail',
  'navigation.apidocumentation': 'API Documentation',
  'navigation.assetmanagement': 'Asset Management',
  'navigation.vendormanagement': 'Vendor Management',
  'navigation.systemhealth': 'System Health',
      
      // Assets translations
      'assets.title': 'Asset Management',
      'assets.description': 'Track and manage your organization\'s assets',
      'assets.loadingAssets': 'Loading assets...',
      'assets.totalAssets': 'Total Assets',
      'assets.totalValue': 'Total Value',
      'assets.maintenanceDue': 'Maintenance Due',
      'assets.assignedAssets': 'Assigned Assets',
      'assets.active': 'active',
      'assets.inactive': 'inactive',
      'assets.currentMarketValue': 'Current market value',
      'assets.next30Days': 'Next 30 days',
      'assets.currentlyAssigned': 'Currently assigned',
      'assets.assets': 'Assets',
      'assets.manageAndTrack': 'Manage and track your organization\'s assets',
      'assets.searchAssets': 'Search assets...',
      'assets.type': 'Type',
      'assets.allTypes': 'All Types',
      'assets.vehicle': 'Vehicle',
      'assets.itHardware': 'IT Hardware',
      'assets.equipment': 'Equipment',
      'assets.furniture': 'Furniture',
      'assets.status': 'Status',
      'assets.allStatus': 'All Status',
      'assets.maintenance': 'Maintenance',
      'assets.retired': 'Retired',
      'assets.currentValue': 'Current Value',
      'assets.location': 'Location',
      'assets.assignedTo': 'Assigned To',
      'assets.unassigned': 'Unassigned',
      'assets.nextService': 'Next Service',
      'assets.purchased': 'Purchased',
      'assets.serial': 'Serial',
      'assets.scheduleMaintenance': 'Schedule Maintenance',
      'assets.assignAsset': 'Assign Asset',
      'assets.addAsset': 'Add Asset',
      'assets.recentMaintenance': 'Recent Maintenance',
      'assets.latestMaintenanceActivities': 'Latest maintenance activities and upcoming services',
      'assets.by': 'By',
      'assets.addNewAsset': 'Add New Asset',
      'assets.registerNewAsset': 'Register a new asset in the system.',
      'assets.assetName': 'Asset Name',
      'assets.category': 'Category',
      'assets.filterByType': 'Filter by type...',
      'assets.assetDescription': 'Asset description',
      'assets.serialNumber': 'Serial Number',
      'assets.model': 'Model',
      'assets.manufacturer': 'Manufacturer',
      'assets.purchaseDate': 'Purchase Date',
      'assets.purchasePrice': 'Purchase Price (EGP)',
      'assets.currentValueEGP': 'Current Value (EGP)',
      'assets.building': 'Building',
      'assets.buildingName': 'Building name',
      'assets.floor': 'Floor',
      'assets.room': 'Room',
      'assets.roomNumber': 'Room number',
      'assets.cancel': 'Cancel',
      'assets.scheduleMaintenanceTitle': 'Schedule Maintenance',
      'assets.scheduleMaintenanceForAsset': 'Schedule maintenance for an asset.',
      'assets.selectAsset': 'Select asset',
      'assets.maintenanceType': 'Maintenance Type',
      'assets.routine': 'Routine',
      'assets.repair': 'Repair',
      'assets.inspection': 'Inspection',
      'assets.upgrade': 'Upgrade',
      'assets.maintenanceDescription': 'Description',
      'assets.describeMaintenanceWork': 'Describe the maintenance work',
      'assets.date': 'Date',
      'assets.estimatedCost': 'Estimated Cost (EGP)',
      'assets.notes': 'Notes',
      'assets.additionalNotes': 'Additional notes',
      'assets.assignAssetTitle': 'Assign Asset',
      'assets.assignAssetToEmployee': 'Assign an asset to an employee.',
      'assets.assignTo': 'Assign To',
      'assets.selectEmployee': 'Select employee',
      'assets.assignmentDate': 'Assignment Date',
      'assets.assignmentNotes': 'Assignment notes',
      'assets.viewDetails': 'View Details',
      'assets.editAsset': 'Edit Asset',
      'assets.maintenanceHistory': 'Maintenance History',
      'assets.viewAnalytics': 'View Analytics',
      'assets.manageAssignment': 'Manage Assignment',
      'assets.deleteAsset': 'Delete Asset'
    };

    // Helper function to get nested value from object
    const getNestedValue = (obj: any, path: string) => {
      return path.split('.').reduce((current, key) => current?.[key], obj);
    };

    // Try to get translation from loaded translations first, then fallback
    let translation = getNestedValue(translations, key) || fallbackTranslations[key] || key;
    
    if (params && typeof params === 'object') {
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(`{${paramKey}}`, params[paramKey]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
