services:
  # Backend API Service
  - type: web
    name: clutch-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://ziadabdelmageed1:I174HSKpqf6iNBKd@clutch.qkgvstq.mongodb.net/?retryWrites=true&w=majority&appName=Clutch
      - key: MONGODB_DB
        value: clutch
      - key: CORS_ORIGIN
        value: https://clutch-a2f49.web.app
      - key: ALLOWED_ORIGINS
        value: https://clutch-a2f49.web.app,https://admin.clutch.com
      - key: PLATFORM_API_URL
        value: https://clutch-main-nk7x.onrender.com
      - key: REDIS_URL
        value: redis://redis-18769.c280.us-central1-2.gce.redns.redis-cloud.com:18769
      - key: REDIS_PASSWORD
        value: 1f1KghLl0pOXlh4JwNRwoGjaZbV6fHi6
      - key: REALTIME_ENABLED
        value: true
      - key: MONITORING_ENABLED
        value: true
      - key: CDN_ENABLED
        value: true
      - key: HELMET_ENABLED
        value: true
      - key: HELMET_CONTENT_SECURITY_POLICY
        value: true
      - key: HELMET_HSTS_MAX_AGE
        value: 31536000
      - key: HELMET_HIDE_POWERED_BY
        value: true
      - key: HELMET_FRAMEGUARD
        value: true
      - key: HELMET_XSS_PROTECTION
        value: true
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Next.js Service
  - type: web
    name: clutch-frontend
    env: node
    plan: starter
    buildCommand: cd client && npm ci --prefer-offline --no-audit && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://clutch-main-nk7x.onrender.com
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
