# Render Configuration for Clutch Backend
# This file configures the deployment on Render platform

services:
  - type: web
    name: clutch-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: AUTO_SETUP_ENABLED
        value: true
      - key: AI_MONITORING_ENABLED
        value: true
      - key: AI_AUTO_FIX_ENABLED
        value: true
      - key: HELMET_ENABLED
        value: true
      - key: RATE_LIMITING_ENABLED
        value: true
      - key: LOG_LEVEL
        value: info
      - key: COMPRESSION_ENABLED
        value: true
      - key: HEALTH_CHECK_ENABLED
        value: true
      - key: METRICS_ENABLED
        value: true
    # Auto-deploy from main branch
    autoDeploy: true
    branch: main
    # Health check configuration
    healthCheckPath: /health
    # Environment variables (set these in Render dashboard)
    # MONGODB_URI
    # JWT_SECRET
    # OPENAI_API_KEY
    # GEMINI_API_KEY
    # DEEPSEEK_API_KEY
    # ANTHROPIC_API_KEY
    # GROK_API_KEY
    # RENDER_API_KEY
    # RENDER_SERVICE_ID
    # BACKEND_URL
    # ADMIN_URL